project:
  type: book
  output-dir: docs

book:
  title: "CASA0023 Learning Diary"
  author: "Duanduan Shen"
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    - week5.qmd
    - week6.qmd
    - week7.qmd
    - week8.qmd

number-sections: false

format:
  html:
    theme: solar
    css: styles.css
